// src/app/emails/PortalNotification.tsx
import {
  Html,
  Head,
  Preview,
  Tailwind,
  Body,
  Container,
  Text,
  Heading,
  Section,
  Row,
  Column,
} from "@react-email/components";
import * as React from "react";

interface PortalNotificationProps {
  userEmail: string;
  changeType: string;
  changeDetails: string;
  timestamp: string;
}

export const PortalNotification = ({
  userEmail,
  changeType,
  changeDetails,
  timestamp,
}: PortalNotificationProps) => {
  return (
    <Html>
      <Head />
      <Preview>Customer Portal Activity - {changeType}</Preview>
      <Tailwind
        config={{
          theme: {
            extend: {},
          },
        }}
      >
        <Body className="bg-white text-base font-sans">
          <Container className="bg-white p-8">
            <Heading className="text-2xl font-bold text-gray-900 mb-6">
              🔔 Customer Portal Activity
            </Heading>

            <Text className="leading-6 text-gray-700">
              A user has made changes to their account through the Customer Portal.
            </Text>

            <Section className="mt-6 p-4 bg-gray-50 rounded-lg">
              <Row>
                <Column>
                  <Text className="font-semibold text-gray-900 mb-2">User Details:</Text>
                  <Text className="text-gray-700">Email: {userEmail}</Text>
                  <Text className="text-gray-700">Change Type: {changeType}</Text>
                  <Text className="text-gray-700">Timestamp: {timestamp}</Text>
                </Column>
              </Row>
            </Section>

            <Section className="mt-4 p-4 bg-blue-50 rounded-lg">
              <Row>
                <Column>
                  <Text className="font-semibold text-blue-900 mb-2">Change Details:</Text>
                  <Text className="text-blue-800 whitespace-pre-line">{changeDetails}</Text>
                </Column>
              </Row>
            </Section>

            <Text className="mt-6 text-sm text-gray-500">
              This notification was automatically generated by VidNarrate's Customer Portal monitoring system.
            </Text>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
};

export default PortalNotification;
